### PR TITLE
Add .babelrc to .npmignore.

### PR DESCRIPTION
**Pull request by setok16**

### CODE REVIEW

**Comment by Chion82** [comment]
Thanks!

**Comment by setok16** [comment]
I think we may need to remove .babelrc from this repository to have the .npmignore to take effect. Should I create another pull request?
Edit: I realize that we might not need to remove .babelrc from the git repo, but I am still seeing a .babelrc file in /node_modules/redux-wait-for-action/ when I perform an npm install.

**Comment by Chion82** [comment]
Yeah please fire another pull request. I don't know about the latest front-end build tools now. Please let me know if this problem is fixed and I will publish the npm package.

**Comment by setok16** [comment]
Oh, I didn't realize that you had to publish the npm package again for the changes to take effect. In that case, I think the problem should be solved and the repository is ready to be published. Thank you.

**Comment by Chion82** [comment]
@setok16 I have just published the npm package 0.0.8 . Please update your dependencies and see if the problem is solved.

**Comment by setok16** [comment]
Hello, I apologize for the delayed response. I will test that out today and
update the GitHub issue accordingly.

**Pull request merged**
